### ISSUE TITLE
在Alfred3.7中报错，这个要怎么修改呢

### ISSUE THREAD

**Issue by lanxiaoha** [MIKUScallion/onigiri_jp_dict#2]
Starting debug for '饭团日语词典'

[2017-10-04 02:13:40][ERROR: input.scriptfilter] Code 1: Traceback (most recent call last):
  File "/Users/lan/Library/Caches/com.runningwithcrayons.Alfred-3/Workflow Scripts/6D3AFFE4-1466-41C2-A23C-34D796EF6A8A", line 8, in <module>
    import main
  File "/Users/lan/Library/Application Support/Alfred 3/Alfred.alfredpreferences/workflows/user.workflow.7EA3BA66-189F-4C92-B577-3E2E6D07AA8B/main.py", line 11, in <module>
    from core import main
ImportError: No module named core

**Comment by MIKUScallion** [comment]
我是跑在 Alfred3.2.1 上的，我看下能不能在 3.7 版本下跑着看看。

**Comment by Akimyou** [comment]
被你吓到了，你是在 Alfred2.7 下跑吧。onigiri_jp_dict 只支持 Alfred3.X 哦。
Alfred 的发布列表，最新是 3.5，是可以运行 onigiri_jp_dict 的。
https://www.alfredapp.com/blog/category/releases/
你可以在 xclient info 上下载到 Alfred3.5 的试用版。
